modelproject/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
  path('signup/', signup_view, name="signup"),
  path('login/', login_view, name="login"),
  path('logout/', logout, name="logout"),
]

modelproject/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('home/', home, name='home'),
    path('<int:id>/', detail, name='detail'),
    path('new/', new, name='new'),
    path('about/', about, name="about"),
    path('genre/indie', indie, name="indie"),
    path('genre/rock', rock, name="rock"),
    path('genre/kpop', kpop, name="kpop"),
    path('genre/pop', pop, name="pop"),
    path('genre/other', other, name="other"),
    path('mycode/', mycode, name="mycode"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('comments_create/<int:id>', comments_create, name="comments_create"),
    path('comments_delete/<int:blog_id>/<int:comment_id>', comments_delete, name="comments_delete"),
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', intro, name="intro"),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

modelproject/blog/models.py
from django.db import models
from account.models import CustomUser
from django.conf import settings

# Create your models here.

class Blog(models.Model):
  genre_choices = [
    ('Indie', 'Indie'),
    ('Rock', 'Rock'),
    ('K-pop', 'K-pop'),
    ('Pop', 'Pop'),
    ('Else', 'Else')
  ]
  user = models.ForeignKey(CustomUser, null=True, on_delete=models.CASCADE)
  pub_date = models.DateTimeField()
  title = models.CharField(max_length=100)
  singer = models.CharField(max_length=100)
  code = models.CharField(max_length=300, null=True, blank=True)
  genre = models.CharField(max_length=10, choices = genre_choices)
  memo = models.TextField(null=True, blank=True)
  lyrics = models.TextField(null=True, blank=True)
  image = models.ImageField(upload_to='blog/', blank=True, null=True)

  def __str__(self):
    return self.title

  def summary(self):
    return self.memo[:70]

class Comment(models.Model):
  post = models.ForeignKey(Blog, null=True, blank=True, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank = True, on_delete=models.CASCADE)
  content = models.CharField(max_length=500)
  created_time = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.content

modelproject/blog/forms.py
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
  class Meta:
    model = Blog
    fields = ['title', 'singer', 'genre', 'image', 'code', 'lyrics', 'memo']

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['content']

modelproject/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from .models import Blog, Comment
from .forms import BlogForm, CommentForm
from django.core.paginator import Paginator


# Create your views here.
def intro(request):
  return render(request, 'intro.html')

def home(request):
  blogs = Blog.objects.order_by('-pub_date')
  query = request.GET.get('query')
  if query:
    blogs = Blog.objects.filter(title__contains=query)
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {'blogs':paginated_blogs})

def about(request):
  return render(request, 'about.html')

def detail(request, id):
  blog = get_object_or_404(Blog, pk=id)
  comment_form = CommentForm()
  comments = Comment.objects.filter(post_id = id).order_by('-created_time')
  return render(request, 'detail.html', {"blog" : blog, "comment_form":comment_form, "comments":comments})

def new(request):
  form = BlogForm()
  if request.method == "POST":
    form = BlogForm(request.POST, request.FILES)
    if form.is_valid():
      new_blog = form.save(commit=False)
      new_blog.pub_date = timezone.now()
      if request.user.is_authenticated:
        new_blog.user = request.user
      new_blog.save()
      return redirect('blog:detail', new_blog.id)
    return redirect('blog:home')
  return render(request, 'new.html', {"form" : form})

def update(request, id):
  update_blog = Blog.objects.get(id=id)
  if request.method == "POST":
    update_blog.title = request.POST["title"]
    update_blog.singer = request.POST["singer"]
    update_blog.code = request.POST["code"]
    update_blog.pub_date = timezone.now()
    update_blog.lyrics = request.POST["lyrics"]
    update_blog.memo = request.POST["memo"]
    update_blog.save()
    return redirect('blog:detail', update_blog.id)
  return render(request, 'update.html', {"blog":update_blog})

def delete(request, id):
  blog = Blog.objects.get(id=id)
  blog.delete()
  return redirect('blog:home')

def comments_create(request, id):
  form = CommentForm(request.POST)
  if form.is_valid():
    finalform = form.save(commit=False)
    finalform.post = get_object_or_404(Blog, pk=id)
    if request.user.is_authenticated:
      finalform.user = request.user
    finalform.save()
  return redirect('blog:detail', id)

def comments_delete(request, blog_id, comment_id):
  comment = Comment.objects.get(pk = comment_id)
  if request.user.is_authenticated:
    comment.delete()
  return redirect('blog:detail', blog_id)

def indie(request):
  blogs = Blog.objects.filter(genre="Indie").order_by('-pub_date')
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {"blogs":paginated_blogs})

def rock(request):
  blogs = Blog.objects.filter(genre="Rock").order_by('-pub_date')
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {"blogs":paginated_blogs})

def kpop(request):
  blogs = Blog.objects.filter(genre="K-pop").order_by('-pub_date')
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {"blogs":paginated_blogs})

def pop(request):
  blogs = Blog.objects.filter(genre="Pop").order_by('-pub_date')
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {"blogs":paginated_blogs})

def other(request):
  blogs = Blog.objects.filter(genre="Else").order_by('-pub_date')
  paginator = Paginator(blogs, 3)
  page = request.GET.get('page')
  paginated_blogs = paginator.get_page(page)
  return render(request, 'home.html', {"blogs":paginated_blogs})

def mycode(request):
  if request.user.is_authenticated:
    blogs = Blog.objects.filter(user = request.user).order_by('-pub_date')
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    return render(request, 'home.html', {"blogs":paginated_blogs})
  else:
    return redirect('account:login')

modelproject/blog/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
  body{
    font-weight: 200;
  }
  .container{
    height:1300px;
  }
  .about{
    text-align: left;
    width:1000px;
    margin-left:300px
  }
  li{
    font-weight:500;
  }
  a{
    text-decoration: none;
    color:gray
  }

</style>

<div class="container"><br>
<h1><b>ABOUT CODEMODE</b></h1>
<br><hr>
<img src="{% static 'about.jpg' %}" style="max-height:510px; float:left">
<div class="about"><h3><b>Purpose</b></h3>
&nbsp&nbsp I like to play songs with various instruments, and especially there are many songs that you can play with guitar.
If you have passion to learn some simple guitar chords, you can enjoy your favorite songs with your own play.
At first I just started to write the song list I learned in my note of my phone(like the picture you can see on the page), 
but I wanted to write some chords information of the song and lyrics together. 
And I thought that it will be great if I can distinguish the songs easily with their picture of album or etc.<br><br><br>
<h3><b>Meaning</b></h3>
&nbsp&nbspThis page is made by <a href="https://www.djangoproject.com/">django</a> (high-level Python web framework that encourages rapid development and clean, pragmatic design),
so I thought that it will be the coding project for chords. CODE means that two words with similar pronounciation 
(plus I think we can find our taste:code when we collect something continuously.), and MODE means passion. 
Additionally about the logo of CODEMODE : I made a guitar-shaped logo using the curves of the alphabet(C-O-D-E-M-O-D-E).<br><br><br>
<h3><b>Functions</b></h3>
<li>INTRO</li>
  There's a interaction page with lyrics of some songs and logos of CODEMODE.</li>
<li>CRUD</li>
  This is a kind of blog made by basic function of django : you can Create, Read, Update, Delete all posts!
  After siginup & login, you can post your code(song) by click "New Post" on homepage and "POST" on nav-bar above every contents.
  By clicking the picture or the name of the songs, you can go to detail page. Then if you're the creator of the page, you can update and delete in the page.
  <li>ABOUT</li>
  This page is about page.
<li>MYCODE</li>
  You can see only your postings by clicking this button.
<li>GENRE</li>
  If you click your favorite genre on the drop-box of GENRE, you'll see the song lists that are fit with your code.<br><br><br>
<h3><b>REFERENCE</b></h3>
&nbsp&nbsp Here are some links that can help your code time!
<li><a href="https://www.all-guitar-chords.com/">Guitar Chords</a></li>
<li><a href="https://cafe.naver.com/tongandtong">tongandtong : naver cafe</a></li>
<li><a href="https://chordify.net/">chordify : instant chords for any song</a></li>
<li><a href="https://www.youtube.com/user/GrabTheGT">GrabTheGuitar : simple and various songs</a></li>
<li><a href="https://www.youtube.com/c/JinsanKim">Guitarist Jinsan Kim's youtube</a></li><br><br>
<h3><b>OTHERS</b></h3>
<li><a href="https://www.djangoproject.com/">DJANGO</a></li>
<li><a href="https://www.instagram.com/likelion_hufs/">HUFS(SEOUL) LIKELION INSTAGRAM</li>
<li><a href="https://github.com/ex-g">GITHUB</a></li><br>
</div>
<hr>
</div>
{% endblock %}

modelproject/blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
  hr{
    width:1200px;
    margin-left:160px
  }
  .container{
    width: 1200px;
    background-color: black;
    border-radius: 7px;
  }
  .lyrics{
    overflow: scroll;
    background-color: white;
    width:600px;
    height:400px;
    margin-left:540px;
    margin-right:40px;
    border-radius: 20px;
    padding:30px
  }
  .code{
    background-color: white;
    margin-left:540px;
    width: 600px;
  }
  .memo{
    background-color: white;
    width:1110px;
    margin-left:30px
  }
  .comment{
    width:700px;
    margin-left:420px;
    padding:10px;
    text-align: left;
    border:solid gray 1px
  }
  .post_admin a{
    text-decoration: none;
    color:gray
  }
</style>
  <body><br>
    <h1><b>{{blog.title}}</h1>
    <b>{{ blog.singer }}</b><br>
    작성자 : {{blog.user.username}}<br>
    날짜: {{blog.pub_date}}<br><br>
    <a style="font-size:20px; color:gray">{{blog.genre}}</a><br>
    <hr><br><br>
    <div class="container">
    {% if blog.image %}
    <img src="{{blog.image.url}}" alt="" style="height:470px; float:left; margin-top: 24px; margin-left:30px">
    {% else %}
    <img src="{% static 'music.png' %}" alt="" style="height:470px; float:left; margin-top: 24px; margin-left:30px">
    {% endif %}<br>
    
    <div class="code">
    <b>code<br>
    {% if blog.code %}
    {{ blog.code }}</b>
    {% endif %}<br></div><br>

    <div class="lyrics">
    {% if blog.lyrics %}
    <b>lyrics</b><br><br><pre><a style="font-family:Gill Sans">{{ blog.lyrics }}</a></pre>
    {% else %}
    <b>lyrics</b><br><br>등록된 가사 없음
    {% endif %}</div><br>

    <div class="memo">
    {% if blog.memo %}<br>
    <b>MEMO</b><br><br><pre><a style="font-family:Gill Sans">{{ blog.memo }}</a></pre><br><br>
    {% endif %}</div><br>
    </div>
  <br><br>
  <div class="post_admin">
  {% if request.user == blog.user %}
  <a href="{% url 'blog:update' blog.id %}">수정하기</a>
  <a href="{% url 'blog:home' %}">돌아가기</a>
  <a href="{% url 'blog:delete' blog.id %}">삭제하기</a>
  {% endif %}
</div>
  <hr>
  <div class="comments">
    <br><br>
    <form action="{% url 'blog:comments_create' blog.id %}" method="POST">
      {% csrf_token %}
      {% if request.user.is_authenticated %}
      <b>{{ request.user }}</b> |
      {% else %}
      <b>익명</b> |
      {% endif %}
      {{ comment_form }}
      <input type="submit" value = "댓글 입력">
      </form>
      {% if comments %}
      <br><br>

      총 {{ comments | length }} 개의 댓글이 있습니다.
      {% endif %}
      <br><br>

    {% for comment in comments %}
    <div class="comment">

    {% if request.user == comment.user %}
    <p style="font-size:12px"><b><span style="color:blue">{{comment.user}} (나)</b></span> | {{comment.created_time}}
    <a href="{% url 'blog:comments_delete' blog.id comment.id %}" style="font-size: 12; color:gray; text-decoration: none; float:right">삭제&nbsp</a></p>
    {% elif comment.user %}
    <p style="font-size:12px"><b>{{comment.user}}</b> | {{comment.created_time}}</p>
    {% else %}
    <p style="font-size:12px"><b>익명</b> | {{comment.created_time}}</p>
    {% endif %}

    {{ comment.content }}
    <br></div><br>
    {% endfor %}
    </div>
{% endblock %}
  </body>

modelproject/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .intro{
    background-color: white;
    color:black
    }
  .container{
    background-color: black;
    margin-bottom: 30px;
    max-width:1000px;
    height:280px;
    border:solid 1px black;
    border-radius: 7px;
  }
  .outside{
    border-radius: 7px;
    border:solid 2px white;
    height:260px;
    margin-top:9px;
  }
  .white{
    background-color: white;
    margin-left:250px;
    margin-right:30px;
    height:210px;
  }
  .paginator a{
    text-decoration: none;
    color:gray
  }
</style>
  <body><br><br>
    <div class="intro">
    <i>find your code with</i><br><br>
    <a href="{% url 'blog:home' %}"><img src="{% static 'codemode.png'%}" style="max-height:100px"></a><br><br><hr><br><br>
    <a href="{% url 'blog:new' %}" style="text-decoration:none; color:black;"><h5>New Post</h5></a><br>
    </div><br><br>
    {% for blog in blogs %}

    <div class="container">
      <div class="outside"><br>
        {% if blog.image %}
        <a href="{% url 'blog:detail' blog.id %}"><img src="{{blog.image.url}}" alt="" style="max-width:210px; margin-left:20px; float:left"></a>
        {% else %}
        <a href="{% url 'blog:detail' blog.id %}"><img src="{% static 'music.png' %}" style="max-width:210px; margin-left:20px; float:left"></a>
        {% endif %}
        <div class="white">
        <br><p style="font-size:13px">{{blog.user}} | {{blog.genre}} | {{ blog.pub_date }}</p>
        <a href="{% url 'blog:detail' blog.id %}" style="text-decoration:none; color:black"><span style="font-size:40px"><b>{{ blog.title }}</b></span></a>
        <br><b>{{blog.singer}}</b><br><br>
      {{ blog.summary }}
      <a href="{% url 'blog:detail' blog.id %}" style="font-size:12px; color:gray; text-decoration: none;"> 자세히 보기</a><br><br><br>
    </div></div></div>
    {% endfor %}

    <div class="paginator">
      {% if blogs.has_previous %}
      <a href="?page=1">처음 |</a>
      <a href="?page={{blogs.previous_page_number}}">이전 </a>&nbsp
      {% endif %}
      <span>{{blogs.number}}</span>
      <span>of</span>
      <span>{{blogs.paginator.num_pages}}</span>
      {% if blogs.has_next %}
      <a href="?page={{blogs.next_page_number}}">&nbsp 다음 |</a>
      <a href="?page={{blogs.paginator.num_pages}}">마지막</a>
      {% endif %}
    </div>
  </body>
{% endblock %}}

modelproject/blog/templates/intro.html
{% load static %}
  <link href="{% static 'intro.css' %}" rel="stylesheet">
<body>


  <div class="wrap">
    <div class="links">
    <span style="font-family:Georgia; font-size:1.5rem"><b><i>Find your code with <a href="{% url 'blog:home' %}" style="color:black">CODEMODE.</i></b></span><br><br>
    <a href="{% url 'blog:home' %}">Go to Home | </a>
    <a href="{% url 'blog:about' %}">About | </a>
    <a href="{% url 'account:login' %}">Login | </a>
    <a href="{% url 'account:signup' %}">Signup </a><br><br><br><br><br></div>

    <a href="{% url 'blog:home' %}" style="text-decoration:none"><img src="{% static 'logo.png' %}" style="max-width:300px">
    <img src="{% static 'codemode.png' %}" style="max-width:300px"></a>
    <br><br><br></div>
    <div class="box"></div>
    <p id="dynamic" class="lg-text"></p>
  <script src="{% static 'intro.js' %}"></script>


</body>

modelproject/blog/templates/new.html
{% extends 'base.html' %}
{% block content %}
<style>
  .unknown a{
    text-decoration: none;
    color: gray
  }
</style>
{% if user.is_authenticated %}
<body><br>
  <h1>Keep Your Code</h1><br>
  <form action="{% url 'blog:new' %}" method="post" enctype="multipart/form-data">
      {%csrf_token%}
      {{ form.as_p }}
      <button type='submit'>작성하기</button>
  </form>
</body>
{% else %}
<body>
  <br><br>
  <div class="unknown">
  <h2>글을 쓰려면 로그인해야 합니다!</h2>
  <h5>Please login before post a new code, or sign up!</h5><br>
  <a href="{% url 'account:login' %}">로그인하기</a>
  <a href="{% url 'blog:home' %}">돌아가기</a><br><br>
  회원이 아니신가요?
  <a href="{% url 'account:signup' %}">회원가입하기</a>
</div>
</body>
{% endif %}
{% endblock %}

modelproject/blog/templates/update.html
{% extends 'base.html' %}
{% block content %}
<h1>Update</h1>
<a style="color:gray">(You can't update image and genre)</a><br><br>
<form action="{% url 'blog:update' blog.id %}" method="POST">
  {% csrf_token %}
  title : <input type="text" name="title" value={{blog.title}}><br><br>
  singer : <input type="text" name="singer" value={{blog.singer}}><br><br>
  code : <input type="text" name="code" value={{blog.code}}><br><br>
  lyrics : <textarea name="lyrics" cols="30" rows="10">{{blog.lyrics}}</textarea><br><br>
  memo : <textarea name="memo" cols="30" rows="10">{{blog.memo}}</textarea><br><br>

  <input type="submit" value="완료">
</form>
{% endblock %}