modelproject/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
  path('signup/', signup_view, name="signup"),
  path('login/', login_view, name="login"),
  path('logout/', logout, name="logout"),
]

modelproject/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('home/', home, name='home'),
    path('<int:id>/', detail, name='detail'),
    path('new/', new, name='new'),
    path('about/', about, name="about"),
    path('genre/indie', indie, name="indie"),
    path('genre/rock', rock, name="rock"),
    path('genre/kpop', kpop, name="kpop"),
    path('genre/pop', pop, name="pop"),
    path('genre/other', other, name="other"),
    path('mycode/', mycode, name="mycode"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('comments_create/<int:id>', comments_create, name="comments_create"),
    path('comments_delete/<int:blog_id>/<int:comment_id>', comments_delete, name="comments_delete"),
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', intro, name="intro"),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

modelproject/modelproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>BLOG</title>
    <style>
      body {
        text-align: center;
        }
      .mynav{
          background-color: black;
        }
      footer a{
        text-decoration:none; 
        color:white
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}"><img src="{% static 'logo.png' %}" style="max-height:50px"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new' %}">POST</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:mycode' %}">MYCODE</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                GENRE
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'blog:indie'%}">Indie</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:rock'%}">Rock</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:kpop'%}">K-pop</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:pop'%}">Pop</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:other'%}">Else</a></li>
                <!-- <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li> -->
              </ul>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li> -->
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user.nickname}}님 안녕하세요!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}" tabindex="-1" aria-disabled="true">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="text" placeholder="Search your code" aria-label="Search" name="query">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class = "my_container">
        {% block content %}
        {% endblock %}
    </div>
    <br><br>
    <div class="footer" style="background-color:gray; color:white">
    <footer>
      <br>
      <a href="{% url 'intro' %}">INTRO</a> | Go to Intro Page<br>
      <a href="{% url 'blog:about' %}">ABOUT</a> | what's CODEMODE?<br>
      <a style="font-size: 10px">@ bella personal assignment - CODEMODE | 0711-0715 | HUFS LIKELION 10th BACKEND</a>
      <br>
    <br>
  </body>
</html>